language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo build --verbose --bins --features=binary
  - cargo test --verbose --features=binary
matrix:
  allow_failures:
    - rust: nightly